language: android

android:
  components:
    - extra-google-m2repository
    - extra-android-m2repository
    - platform-tools
    - build-tools-26.0.2
    - android-24
    - android-26
    - sys-img-armeabi-v7a-android-24

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  # install Mini Connected
  - wget --inet4-only https://hufman.me/MINI_Connected_Classic_v1.1.3_apkpure.com.apk -O connected.apk
  - adb install connected.apk
  - pip install --user xunitparser

script:
  - bash ./gradlew build connectedCheck

after_script:
  - python buildtools/xunit_summary.py build/outputs/androidTest-results/connected/*.xml
