name: build

on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build the project
        run: ./gradlew build --stacktrace

  instrumentedTest:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        api: [28, 30]
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Prepare cached external dependencies
        uses: actions/cache@v2
        with:
          key: external_${{ hashFiles('.github/actions/download-externals-action/download.sh') }}
          path: |
            external
      - name: Download build dependencies
        uses: ./.github/actions/download-externals-action

      - name: Build the project
        run: ./gradlew build --stacktrace
      - name: Run Android Connected Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api }}
          target: google_apis
          script: |
            adb install -g 'external/MINI_Connected_Classic_v1.1.3_(usa_160214_448)_apkpure.com.apk'
            adb install -g 'external/iHeartRadio_for_Auto_v1.12.2_apkpure.com.apk'
            sleep 10
            adb logcat -c
            (./gradlew connectedCheck || adb logcat -d; exit ${PIPESTATUS[0]})
      - name: Summarize test results
        run: python3 -m pip install --user xunitparserx && python3 buildtools/xunit_summary.py build/outputs/androidTest-results/connected/flavors/*/*.xml