name: build

on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Build the project
        run: ./gradlew build --stacktrace

  instrumentedTest:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        api: [28, 30]
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Prepare cached external dependencies
        uses: actions/cache@v4
        with:
          key: external_${{ hashFiles('.github/actions/download-externals-action/download.sh') }}
          path: |
            external
      - name: Download build dependencies
        uses: ./.github/actions/download-externals-action

      - name: Build the project
        run: ./gradlew build --stacktrace

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Create directory for AVD
        run: mkdir -p $HOME/.android/avd

      - name: Run Android Connected Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api }}
          target: google_apis
          script: |
            adb install -g 'external/MINI_Connected_Classic_v1.1.3_(usa_160214_448)_apkpure.com.apk'
            adb install -g 'external/iHeartRadio_for_Auto_v1.12.2_apkpure.com.apk'
            sleep 10
            adb logcat -c
            bash -c './gradlew connectedCheck || adb logcat -d; exit ${PIPESTATUS[0]}'
      - name: Summarize test results
        run: python3 -m pip install --user xunitparserx --break-system-packages && python3 buildtools/xunit_summary.py build/outputs/androidTest-results/connected/*/*.xml